export enum ParserDomain {
  YANDEX = 'realty.ya.ru',
  CIAN = 'cian.ru',
  AVITO = 'avito.ru',
  YOULA = 'youla.ru',
  DOMCLICK = 'domclick.ru',
  ENCO = 'enco72.ru',
  STRANA = 'strana.com',
  TDSK = 't-dsk.ru',
  METRIKA = 'metrika.com',
  SOVA = 'sova72.ru',
  FOUR_DEVELOPMENT = '4d.life',
  REALT = 'realt.by',
  KRISHA = 'krisha.kz',
  SAMOLET_PLUS = 'samoletplus.ru',
  MIRKVARTIR = 'mirkvartir.ru',
  DOSKA = 'doska.ykt.ru',
  NAVIGATOR = 'navigator-tmn.ru',
  FARPOST = 'farpost.ru',
  ETAGI = 'etagi.com',
  OLAN = 'olan.ru',
  MOVE = 'move.ru',
  REALTY_1777 = 'realty.1777.ru',
  M2 = 'm2.ru',
}
